export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const PRODUCT_DELETED_SUCCESS = 'PRODUCT_DELETED_SUCCESS';
export const PRODUCT_EDITED_SUCCESS = 'PRODUCT_EDITED_SUCCESS';
export const PRODUCT_EDIT = 'PRODUCT_EDIT';

export const HAVE_ERROR = 'HAVE_ERROR';
export const SHOW_LOADING = 'SHOW_LOADING';


